language: cpp
install:
  - apt-get install libgmp3-dev
  - apt-get install libsodium-dev
script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build . -- -j 6
  - ./src/runtest
compiler:
  - clang
